### ISSUE TITLE
emit events

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/map-config#3]
following up on a conversation @doowb and I had about potentially exposing some property or method for getting keys of mapping methods, this seems like the best compromise since it would allow the user to do whatever they want with the data.

**Comment by doowb** [comment]
Added the `.keys` array via https://github.com/doowb/map-config/commit/8f53d06113391a45e592e8743b17e9dc9c5316f0

I think this should be good instead of emitting.

**Comment by jonschlinkert** [comment]
agreed!
